### PR TITLE
Fix parsing aud jwt claim

### LINKED ISSUE #8088: JWT parser doesn't support aud claim array
The JWT parser currently verifies the `aud` claim using a direct comparison with the client ID:
https://github.com/roundcube/roundcubemail/blob/f7ba562bed77a3fbdf70308e345f34c8f03f1cff/program/include/rcmail_oauth.php#L151-L153

However, according to [RFC7519](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3), the `aud` claim is an array of case-sensitive strings, which _may_ be shortened to just a case-sensitive string (without the wrapping array) if there is only one.

The current code fails in the default case, since it doesn't take arrays into account. Instead, the code should check whether the client ID is one of the strings in the array.

### PR DESCRIPTION
**Pull request by invliD**
Fixes #8088.

### CODE REVIEW

File: program/include/rcmail_oauth.php [hunk 1]
```diff
@@ -148,7 +148,7 @@ public function jwt_decode($jwt)
         if (isset($body['azp']) && $body['azp'] !== $this->options['client_id']) {
             throw new RuntimeException('Failed to validate JWT: invalid azp value');
         }
-        else if (isset($body['aud']) && $body['aud'] !== $this->options['client_id']) {
+        else if (isset($body['aud']) && (is_array($body['aud']) ? !in_array($this->options['client_id'], $body['aud']) : $body['aud'] !== $this->options['client_id'])) {
```
Comment (alecpl) [inline program/include/rcmail_oauth.php:151]: This line is quite long, I would probably do: `(isset($body['aud']) && !in_array($this->options['client_id'], (array) $body['aud']))`.

File: tests/Rcmail/Oauth.php [hunk 2]
```diff
@@ -28,6 +28,34 @@ function test_jwt_decode()
...
     }
 
+    /**
+     * Test jwt_decode() method with an array aud
+     */
+    function test_jwt_decode_array()
+    {
+        $jwt = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImF1ZCI6WyJzb21lLWNsaWVudCJdfQ.signature';
+
+        $oauth = new rcmail_oauth(array(
```
Comment (alecpl) [inline tests/Rcmail/Oauth.php:38]: Short array syntax, please. Here and below.

**Review by alecpl — CHANGES_REQUESTED** [review]
And you added tests, great.
